"""Add google_sub and email to User

Revision ID: 88222e441266
Revises: d2691da720f7
Create Date: 2025-06-07 03:48:45.880238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88222e441266'
down_revision = 'd2691da720f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_google_sub', ['google_sub'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_google_sub', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('google_sub')

    # ### end Alembic commands ###
