"""Initial migration after reset

Revision ID: d2691da720f7
Revises: 
Create Date: 2025-06-04 14:26:02.928982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2691da720f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('details_needed', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_email_store_uc', ['email', 'store_id'])
        batch_op.create_unique_constraint('_phone_number_store_uc', ['phone_number', 'store_id'])
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_name_store_uc', ['name', 'store_id'])
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'store', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_name_store_uc', type_='unique')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_phone_number_store_uc', type_='unique')
        batch_op.drop_constraint('_email_store_uc', type_='unique')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('details_needed')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
